---
#https://wiki.archlinux.org/title/Systemd-resolved
- name: Populate service facts
  ansible.builtin.service_facts:

- name: Enable service systemd-resolved and ensure it started is not masked
  ansible.builtin.systemd:
    name: avahi-daemon
    enabled: no
    state: stopped
    masked: yes
  when: "'avahi-daemon' in services"
  
- name: Remove package openresolv as it conflicts with systemd-resolvconf
  community.general.pacman:
    name: openresolv
    state: absent
    
- name: Install package systemd-resolvconf from repo
  community.general.pacman:
    name: systemd-resolvconf
    state: present

- name: Copy resolved.conf.j2 /etc/systemd/resolved.conf
  template:
    src: resolved.conf.j2
    dest: /etc/systemd/resolved.conf
  become: yes        
  notify:
    - systemd-resolved restart
    
- name: Enable service systemd-resolved and ensure it started is not masked
  ansible.builtin.systemd:
    name: systemd-resolved
    enabled: yes
    state: started
    masked: no
  
- name: Create a symbolic link /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
  ansible.builtin.file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    force: yes
    owner: root
    group: root
    state: link
    mode: '1777'
